resource_group_name         = "tejit-actions-test"
resource_group_location     = "eastus"
virtual_network_name        = "vnet2021"
subnet_name                 = "subnet2021"
public_ip_name              = "publicip2021"
network_security_group_name = "nsgprod2021"
network_interface_name      = "nicprod2021"
linux_virtual_machine_name  = "linuxvm2021"