name: 'powershell-workflow'

on:
  workflow_dispatch:

jobs:

  deploy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted


    steps:

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}

    - uses: actions/checkout@v1
    - name: Run PowerShell Hello World script
      # if: github.event.action == 'inline'
      run: Write-Output 'Hello World!'
    - name: Run a multi-line PowerShell script
      # if: github.event.action == 'inline'
      run: |
        $psversiontable;
        Get-Process;
