name: 'powershell-workflow'

on:
  workflow_dispatch:

jobs:

  deploy:
    #runs-on: ubuntu-latest
    runs-on: self-hosted


    steps:

    # env:
    #   GITHUB_WORKSPACE: ${{ toJSON(github) }}
    # - name: Login to Azure
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS}}

    - uses: actions/checkout@v1
    - name: Run PowerShell Hello World script
      # if: github.event.action == 'inline'
      run: Write-Output $GITHUB_WORKSPACE
        

    
    - name: Run PowerShell Test script
      run: ".\script2.ps1" 
      shell: powershell
      # run: pwsh -command ".\$GITHUB_WORKSPACE\script2.ps1"


    # - name: Dump GitHub context
    #   run: echo "$GITHUB_w"
      
